version: '3'

services:
  rabbitmq:
    image: rabbitmq:alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
volumes:
  database_data:
  networks: